In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../Global_Financial_Analysis/Global_Financial_Data.csv")

In [3]:
df

,Unnamed: 0.1,Unnamed: 0,Date,Close,High,Low,Open,Volume,Company,Country,Adj Close
0,0,0,2026-01-01,1568.348511,1585.170755,1563.869221,1566.457231,6408128.0,Reliance,India,NaN
1,1,1,2026-01-02,1584.971802,1587.261144,1570.936597,1572.728361,6602230.0,Reliance,India,NaN
2,2,2,2026-01-05,1570.837036,1604.382010,1568.049996,1585.668486,8704973.0,Reliance,India,NaN
3,3,3,2026-01-06,1500.661499,1561.778940,1489.413578,1561.778940,27417125.0,Reliance,India,NaN
4,4,4,2026-01-07,1497.277100,1513.004431,1491.105683,1503.050455,11199340.0,Reliance,India,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15290,2055,2055,2026-06-02,1387.000000,1394.500000,1366.500000,1372.000000,16234300.0,Honda,Tokyo,NaN
15291,2056,2056,2026-06-03,1496.500000,1537.000000,1392.000000,1410.000000,55737500.0,Honda,Tokyo,NaN
15292,2057,2057,2026-06-04,1504.500000,1514.000000,1483.000000,1495.000000,23709300.0,Honda,Tokyo,NaN
15293,2058,2058,2026-06-05,1444.500000,1503.000000,1444.500000,1495.000000,20119800.0,Honda,Tokyo,NaN
15294,2059,2059,2026-06-08,1438.500000,1452.000000,1421.000000,1425.500000,20146800.0,Honda,Tokyo,NaN

In [4]:
df=df.drop('Unnamed: 0.1', axis=1)

In [5]:
df

,Unnamed: 0,Date,Close,High,Low,Open,Volume,Company,Country,Adj Close
0,0,2026-01-01,1568.348511,1585.170755,1563.869221,1566.457231,6408128.0,Reliance,India,NaN
1,1,2026-01-02,1584.971802,1587.261144,1570.936597,1572.728361,6602230.0,Reliance,India,NaN
2,2,2026-01-05,1570.837036,1604.382010,1568.049996,1585.668486,8704973.0,Reliance,India,NaN
3,3,2026-01-06,1500.661499,1561.778940,1489.413578,1561.778940,27417125.0,Reliance,India,NaN
4,4,2026-01-07,1497.277100,1513.004431,1491.105683,1503.050455,11199340.0,Reliance,India,NaN
...,...,...,...,...,...,...,...,...,...,...
15290,2055,2026-06-02,1387.000000,1394.500000,1366.500000,1372.000000,16234300.0,Honda,Tokyo,NaN
15291,2056,2026-06-03,1496.500000,1537.000000,1392.000000,1410.000000,55737500.0,Honda,Tokyo,NaN
15292,2057,2026-06-04,1504.500000,1514.000000,1483.000000,1495.000000,23709300.0,Honda,Tokyo,NaN
15293,2058,2026-06-05,1444.500000,1503.000000,1444.500000,1495.000000,20119800.0,Honda,Tokyo,NaN
15294,2059,2026-06-08,1438.500000,1452.000000,1421.000000,1425.500000,20146800.0,Honda,Tokyo,NaN

In [6]:
df=df.drop('Unnamed: 0', axis=1)

In [7]:
df

,Date,Close,High,Low,Open,Volume,Company,Country,Adj Close
0,2026-01-01,1568.348511,1585.170755,1563.869221,1566.457231,6408128.0,Reliance,India,NaN
1,2026-01-02,1584.971802,1587.261144,1570.936597,1572.728361,6602230.0,Reliance,India,NaN
2,2026-01-05,1570.837036,1604.382010,1568.049996,1585.668486,8704973.0,Reliance,India,NaN
3,2026-01-06,1500.661499,1561.778940,1489.413578,1561.778940,27417125.0,Reliance,India,NaN
4,2026-01-07,1497.277100,1513.004431,1491.105683,1503.050455,11199340.0,Reliance,India,NaN
...,...,...,...,...,...,...,...,...,...
15290,2026-06-02,1387.000000,1394.500000,1366.500000,1372.000000,16234300.0,Honda,Tokyo,NaN
15291,2026-06-03,1496.500000,1537.000000,1392.000000,1410.000000,55737500.0,Honda,Tokyo,NaN
15292,2026-06-04,1504.500000,1514.000000,1483.000000,1495.000000,23709300.0,Honda,Tokyo,NaN
15293,2026-06-05,1444.500000,1503.000000,1444.500000,1495.000000,20119800.0,Honda,Tokyo,NaN
15294,2026-06-08,1438.500000,1452.000000,1421.000000,1425.500000,20146800.0,Honda,Tokyo,NaN

In [8]:
df.Date =df.Date.astype('datetime64[ns]')

In [9]:
df

,Date,Close,High,Low,Open,Volume,Company,Country,Adj Close
0,2026-01-01,1568.348511,1585.170755,1563.869221,1566.457231,6408128.0,Reliance,India,NaN
1,2026-01-02,1584.971802,1587.261144,1570.936597,1572.728361,6602230.0,Reliance,India,NaN
2,2026-01-05,1570.837036,1604.382010,1568.049996,1585.668486,8704973.0,Reliance,India,NaN
3,2026-01-06,1500.661499,1561.778940,1489.413578,1561.778940,27417125.0,Reliance,India,NaN
4,2026-01-07,1497.277100,1513.004431,1491.105683,1503.050455,11199340.0,Reliance,India,NaN
...,...,...,...,...,...,...,...,...,...
15290,2026-06-02,1387.000000,1394.500000,1366.500000,1372.000000,16234300.0,Honda,Tokyo,NaN
15291,2026-06-03,1496.500000,1537.000000,1392.000000,1410.000000,55737500.0,Honda,Tokyo,NaN
15292,2026-06-04,1504.500000,1514.000000,1483.000000,1495.000000,23709300.0,Honda,Tokyo,NaN
15293,2026-06-05,1444.500000,1503.000000,1444.500000,1495.000000,20119800.0,Honda,Tokyo,NaN
15294,2026-06-08,1438.500000,1452.000000,1421.000000,1425.500000,20146800.0,Honda,Tokyo,NaN